/**
 * Shared TypeScript interfaces for transcript-mcp-claude
 */

// ============================================================
// Core Data Types
// ============================================================

export interface Segment {
  start: number;
  end: number;
  duration?: number;
  text: string;
}

export interface WhisperResult {
  detected_language: string;
  language_probability: number;
  duration: number;
  text: string;
  segmentCount: number;
  segments: Segment[];
  error?: string;
}

export interface Config {
  PORT: number;
  HOST: string;
  DEFAULT_LANG: string;
  WHISPER_MODEL: string;
  WHISPER_COMPUTE_TYPE: string;
  MAX_AUDIO_DURATION: number;
  MAX_VDO_DURATION: number;
  TEMP_DIR: string;
}

// ============================================================
// YouTube Types
// ============================================================

export interface TranscriptResult {
  videoID: string;
  title: string;
  lang: string;
  segmentCount: number;
  text: string;
  segments: Segment[];
  method: string;
}

export interface LanguageInfo {
  code: string;
  name: string;
  kind: string;
}

export interface VideoInfo {
  videoID: string;
  title: string;
  author: string;
  lengthSeconds: number;
  viewCount: number;
  description: string;
  availableLanguages: LanguageInfo[];
  method: string;
}

export interface CaptionTrack {
  languageCode: string;
  name: string;
  kind: string;
  isAutoGenerated: boolean;
}

export interface CaptionInfo {
  videoID: string;
  title: string;
  captions: CaptionTrack[];
}

// ============================================================
// Audio / Video Info Types
// ============================================================

export interface AudioFileInfo {
  file: string;
  duration: number;
  format: string;
  format_long: string;
  sample_rate: number;
  channels: number;
  channel_layout: string;
  codec: string;
  bitrate: number;
  size_bytes: number;
}

export interface AudioTranscriptResult {
  file: string;
  lang: string;
  model: string;
  method: string;
  detected_language: string;
  language_probability: number;
  duration: number;
  text: string;
  segmentCount: number;
  segments: Segment[];
}

export interface VdoFileInfo {
  file: string;
  duration: number;
  format: string;
  format_long: string;
  width: number;
  height: number;
  resolution: string | null;
  fps: number | null;
  video_codec: string | null;
  audio_codec: string | null;
  sample_rate: number;
  channels: number;
  bitrate: number;
  size_bytes: number;
}

export interface VdoTranscriptResult {
  file: string;
  lang: string;
  model: string;
  method: string;
  duration: number;
  resolution: string | null;
  detected_language: string;
  language_probability: number;
  text: string;
  segmentCount: number;
  segments: Segment[];
}

// ============================================================
// Subtitle Types
// ============================================================

export interface SubtitleExportResult {
  format: string;
  segment_count: number;
  content: string;
}

export interface SubtitleTimingResult {
  offset_ms: number;
  segment_count: number;
  segments: Segment[];
}

// ============================================================
// Chapter Types
// ============================================================

export interface Chapter {
  index: number;
  start_time: number;
  start_formatted: string;
  preview_text: string;
  title?: string;
}

export interface ChaptersResult {
  total_duration?: number;
  chapter_count?: number;
  chapters?: Chapter[];
  youtube_format?: string;
  segments?: Segment[];
  text?: string;
  max_chapters?: number;
  instruction: string;
}

export interface ChaptersYoutubeResult {
  youtube_description: string;
  chapter_count: number;
}

// ============================================================
// Translation Types
// ============================================================

export interface TranslationPrep {
  source_language: string;
  target_language: string;
  original_text: string;
  original_segment_count: number;
  segments: Segment[];
  instruction: string;
}

export interface MultilingualSubtitlesPrep {
  original_text: string;
  original_segment_count: number;
  segments: Segment[];
  requested_languages: string[];
  instruction: string;
}

// ============================================================
// Summarization Types
// ============================================================

export interface SummarizationPrep {
  original_text: string;
  word_count: number;
  style: string;
  max_length: number;
  instruction: string;
}

export interface KeyMomentsPrep {
  original_text: string;
  segment_count: number;
  segments: Segment[];
  instruction: string;
}

export interface BlogPostPrep {
  original_text: string;
  word_count: number;
  suggested_title: string;
  tone: string;
  instruction: string;
}

// ============================================================
// Batch Types
// ============================================================

export interface BatchItemResult {
  source: string;
  type: string;
  status: string;
  error?: string;
  note?: string;
  [key: string]: unknown;
}

export interface BatchResult {
  total: number;
  successful: number;
  failed: number;
  results: BatchItemResult[];
}

export interface FolderScanEmpty {
  folder: string;
  extensions: string[];
  total_files: number;
  message: string;
}

// ============================================================
// ffprobe Types
// ============================================================

export interface ProbeStream {
  codec_type: string;
  codec_name?: string;
  sample_rate?: string;
  channels?: number;
  channel_layout?: string;
  width?: number;
  height?: number;
  r_frame_rate?: string;
}

export interface ProbeFormat {
  duration?: string;
  format_name?: string;
  format_long_name?: string;
  bit_rate?: string;
  size?: string;
}

export interface ProbeData {
  streams: ProbeStream[];
  format: ProbeFormat;
}

// ============================================================
// Tool Input Args
// ============================================================

export interface YouTubeArgs {
  url: string;
  lang?: string;
}

export interface AudioTranscribeArgs {
  file_path?: string;
  url?: string;
  lang?: string;
  model_size?: string;
}

export interface AudioInfoArgs {
  file_path?: string;
  url?: string;
}

export interface VdoTranscribeArgs {
  file_path?: string;
  url?: string;
  lang?: string;
  model_size?: string;
}

export interface VdoInfoArgs {
  file_path?: string;
  url?: string;
}

export interface TranslateArgs {
  text: string;
  segments?: Segment[];
  target_language: string;
  source_language?: string;
}

export interface MultilingualArgs {
  text: string;
  segments?: Segment[];
  target_languages: string[];
}

export interface SummarizeArgs {
  text: string;
  style?: string;
  max_length?: number;
}

export interface KeyMomentsArgs {
  text: string;
  segments?: Segment[];
}

export interface BlogPostArgs {
  text: string;
  title?: string;
  tone?: string;
}

export interface GenerateChaptersArgs {
  text?: string;
  segments?: Segment[];
  max_chapters?: number;
  min_chapter_duration?: number;
}

export interface FormatChaptersArgs {
  chapters: Chapter[];
}

export interface ExportSubtitlesArgs {
  segments: Segment[];
  format?: string;
  max_chars_per_line?: number;
  max_lines?: number;
}

export interface ConvertSubtitleArgs {
  content: string;
  source_format?: string;
  target_format: string;
}

export interface AdjustTimingArgs {
  segments: Segment[];
  offset_ms: number;
}

export interface BatchTranscribeArgs {
  sources: string[];
  lang?: string;
  model_size?: string;
}

export interface TranscribeFolderArgs {
  folder_path: string;
  extensions?: string[];
  lang?: string;
  model_size?: string;
  recursive?: boolean;
}
